
export interface Images {
    aiIcon: string;
    aiBackground: string;
    avatar1: string;
    avatar2: string;
    barcodeReaderIcon: string;
    barcodeReaderSoft: string;
    barcodeReader: string;
    camera: string;
    customerSupportAvatar: string;
    dataAnalysisIcon: string;
    dataAnalysis: string;
    digitalTwin3D: string;
    endCommunication: string;
    endOfLineIcon: string;
    endOfLine: string;
    fullstackIcon: string;
    headerBg: string;
    heroVideo: string;
    imageProcessingIcon: string;
    imageSoft: string;
    industrialIcon: string;
    innovation1: string;
    innovation2: string;
    innovation3: string;
    inventoryIcon: string;
    inventory: string;
    logo: string;
    mediaGif1: string;
    mediaGif2: string;
    middle: string;
    missionIcon: string;
    mobileDesign: string;
    mobileDev: string;
    moon: string;
    notification: string;
    sideImageLeft: string;
    sideImageRight: string;
    smartWarehouseIcon: string;
    smartWarehouse: string;
    sun: string;
    techAnimation: string;
    visionIcon: string;
    warehouseSoft: string;
    webDesign: string;
    webDev: string;
    logoDark: string;
  }
  
  export const images: Images = {
    aiIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/AI-icon.png",
    aiBackground: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/ai_background.gif",
    avatar1: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/avatar1.jpg",
    avatar2: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/avatar2.jpg",
    barcodeReaderIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/barcode-reader-icon.png",
    barcodeReaderSoft: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/barcode-reader-soft.png",
    barcodeReader: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/barcode-reader.png",
    camera: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/camera.png",
    customerSupportAvatar: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/customer-support-avatar.svg",
    dataAnalysisIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/data-analysis-icon.png",
    dataAnalysis: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/data-analysis.png",
    digitalTwin3D: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/digital-twin-3d.png",
    endCommunication: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/end-cominication.png",
    endOfLineIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/end-of-line-icon.png",
    endOfLine: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/end-of-line.png",
    fullstackIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/fullstack-icon.png",
    headerBg: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/header_bg.png",
    heroVideo: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/hero-video.mp4",
    imageProcessingIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/image-processing-icon.png",
    imageSoft: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/image-soft.png",
    industrialIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/industrial-icon.png",
    innovation1: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/innovation1.png",
    innovation2: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/innovation2.png",
    innovation3: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/innovation3.jpg",
    inventoryIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/inventory-icon.png",
    inventory: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/inventory.png",
    logo: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/logo.svg",
    mediaGif1: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/mediaGif1.gif",
    mediaGif2: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/mediaGif2.gif",
    middle: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/middle.svg",
    missionIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/mission-icon.png",
    mobileDesign: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/mobile-design.png",
    mobileDev: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/mobile-dev.png",
    moon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/moon.svg",
    notification: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/notification.gif",
    sideImageLeft: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/sideImageLeft.png",
    sideImageRight: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/sideImageRight.png",
    smartWarehouseIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/smart-warehouse-icon.png",
    smartWarehouse: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/smart-warehouse.png",
    sun: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/sun.svg",
    techAnimation: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/tech-animation.mp4",
    visionIcon: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/vision-icon.png",
    warehouseSoft: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/warehouse-soft.png",
    webDesign: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/web-design.png",
    webDev: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/web-dev.png",
    logoDark: "https://raw.githubusercontent.com/tiamatech/reactfront/yenibranc/logoDark.png",
  };
  